### ISSUE TITLE
Reset count on new version?

### ISSUE THREAD

**Issue by timothystewart6** [r2d2rigo/UniversalRateReminder#1]
Hi.  It would be nice to have the option to reset the count on a new version.

**Comment by timothystewart6** [comment]
this can be closed.  My changes were merged:  https://github.com/r2d2rigo/UniversalRateReminder/pull/2

**Comment by r2d2rigo** [comment]
@timothystewart6 UniversalRateReminder 2.0 is live on NuGet featuring Windows 10 support and your contribution. Thank you!

**Comment by timothystewart6** [comment]
thank you!
