### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by lorenzofar** [r2d2rigo/UniversalRateReminder#3]
There are some errors in the code, i'll fix them and i'll upload an update.

**Comment by r2d2rigo** [comment]
Hello @lorenzofar and thanks for your collaboration! I'm in the middle of updating the library with new functionality so it can be used in the latest DVLUP challenges (mainly adding the option to contact via email) and the current version of the code can be broken.

Can we coordinate so we don't make any duplicate changes?

**Comment by lorenzofar** [comment]
Ok, i tweaked the project to make it work on windows 10 (also with the feedback popup). I can fix some bugs in the URI and i can add the feedback popup

**Comment by r2d2rigo** [comment]
Feel free to send a pull request when you consider it done! I will look for any further enhancements and publish a signed version in NuGet straight away.

**Comment by r2d2rigo** [comment]
Sorry - I wanted to finish it this weekend and went ahead with it. However feel free to send a pull request this way when you are done and I will cherrypick any new additions made by you!
