### ISSUE TITLE
Microsoft Store review url

### ISSUE THREAD

**Issue by lorenzofar** [r2d2rigo/UniversalRateReminder#4]
The actual version is now using the following URI to open the rate & review page: 
ms-windows-store://pdp/?ProductId=
However, this URI only opens the store page of the app.
To open the rate dialog you can use other URIs like: 
ms-windows-store://review/?ProductId=

**Comment by r2d2rigo** [comment]
Weird - I swear I tested it and the rating section of the store opened (at least in desktop), I will check it later and fix it. Thanks for the heads up!
