### ISSUE TITLE
Feedback dialog does not appear

### ISSUE THREAD

**Issue by lorenzofar** [r2d2rigo/UniversalRateReminder#5]
In the actual version the feedback dialog is not opened, and the first button has a command that opens the store.

**Comment by r2d2rigo** [comment]
You have to open it manually - please check the sample project on the repo and disregard the readme since it's out of date.

**Comment by lorenzofar** [comment]
Ok, maybe i made I was confused with the old version. However i created a pull request in which the feedback dialog is showed depending on the bool AskForFeedback. Maybe you should change the default values for feedback dialog and buttons.
